import type { Metadata, Viewport } from "next";
import { Azeret_Mono, Schibsted_Grotesk } from "next/font/google";
import { connection } from "next/server";

import { AppShell } from "@/components/app-shell";
import { ObservatoryPageMotion } from "@/components/lab/observatory-page-motion";
import { LabGlobalNavigation } from "@/components/lab/lab-global-navigation";
import { SkipLink } from "@/components/skip-link";
import { getCurrentUser } from "@/lib/auth";
import { isLocalPreviewMode, isObservatoryMode } from "@/lib/env";

import "./globals.css";
import "./components.css";
import "./responsive.css";
import "./personal-lab.css";
import "./health-redesign.css";
import "./motion-entry.css";
import "./motion-journal.css";
import "./motion-matrix.css";
import "./dark-lab-preview.css";
import "./lab-worlds-observatory-strata.css";
import "./lab-worlds-index-atelier.css";
import "./lab-arrival.css";
import "./lab-arrival-observatory-strata.css";
import "./lab-arrival-index-atelier.css";
import "./lab-arrival-art.css";
import "./lab-continuous.css";
import "./lab-continuous-worlds.css";
import "./lab-final.css";
import "./lab-final-observatory.css";
import "./lab-final-focus.css";
import "./lab-final-index.css";
import "./observatory-geometry.css";
import "./observatory-deep.css";
import "./observatory-pages.css";

const schibsted = Schibsted_Grotesk({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  variable: "--font-soma-sans",
});

const azeretMono = Azeret_Mono({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  variable: "--font-soma-mono",
});

export const metadata: Metadata = {
  title: "Soma",
  applicationName: "Soma",
  description: "A personal health laboratory to understand the relationships between sleep, recovery, movement, and performance.",
  icons: {
    icon: [{ url: "/icon.png?v=soma-symbol-1", type: "image/png" }],
    shortcut: [{ url: "/favicon.ico?v=soma-symbol-1" }],
    apple: [{ url: "/apple-icon.png?v=soma-symbol-1", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    capable: true,
    title: "Soma",
    statusBarStyle: "black-translucent",
  },
  verification: {
    google: "vN4Hbw8JsncwAf_vQailk6Xw0Wrh7awEsPtmaVoJWL8",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "dark",
  themeColor: "#050505",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // A fresh request is required so Next.js can attach the per-request CSP nonce
  // generated by proxy.ts to framework and hydration scripts.
  await connection();
  const user = await getCurrentUser();
  const localPreview = isLocalPreviewMode();
  const darkInterface = isObservatoryMode();
  const observatoryMode = darkInterface && Boolean(user);

  return (
    <html className={`${schibsted.variable} ${azeretMono.variable}`} lang="en" data-lab-theme={darkInterface ? "observatory" : undefined} data-scroll-behavior="smooth" suppressHydrationWarning>
      <body className={[localPreview && "local-preview", observatoryMode && "observatory-mode"].filter(Boolean).join(" ") || undefined}>
        <SkipLink />
        {localPreview && <div className="preview-banner" role="status"><strong>LOCAL PREVIEW</strong><span>Demo data · Nothing is transmitted or saved</span></div>}
        {observatoryMode && <><LabGlobalNavigation /><ObservatoryPageMotion /></>}
        <AppShell user={user} localPreview={localPreview}>{children}</AppShell>
      </body>
    </html>
  );
}
