import type { Metadata, Viewport } from "next";
import { Figtree } from "next/font/google";
import { connection } from "next/server";

import { AppShell } from "@/components/app-shell";
import { getCurrentUser } from "@/lib/auth";

import "./globals.css";
import "./product-flows.css";

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-soma",
});

export const metadata: Metadata = {
  title: {
    default: "Soma — Understand your health",
    template: "%s · Soma",
  },
  description: "Personal health insights from your sleep, recovery, and activity data.",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0b1210",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // A fresh request is required so Next.js can attach the per-request CSP nonce
  // generated by proxy.ts to framework and hydration scripts.
  await connection();
  const user = await getCurrentUser();

  return (
    <html className={figtree.variable} lang="en" data-scroll-behavior="smooth">
      <body>
        <a className="skip-link" href="#main-page-content">Skip to content</a>
        <AppShell user={user}>{children}</AppShell>
      </body>
    </html>
  );
}
