import type { Metadata, Viewport } from "next";
import { Azeret_Mono, Newsreader, Schibsted_Grotesk } from "next/font/google";
import { connection } from "next/server";

import { AppShell } from "@/components/app-shell";
import { SkipLink } from "@/components/skip-link";
import { ThemeInitializer } from "@/components/theme-toggle";
import { getCurrentUser } from "@/lib/auth";
import { isLocalPreviewMode } from "@/lib/env";

import "./globals.css";
import "./components.css";
import "./responsive.css";

const schibsted = Schibsted_Grotesk({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  variable: "--font-soma-sans",
});

const newsreader = Newsreader({
  subsets: ["latin"],
  weight: "variable",
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-soma-serif",
});

const azeretMono = Azeret_Mono({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  variable: "--font-soma-mono",
});

export const metadata: Metadata = {
  title: {
    default: "Soma — Personal Health Atlas",
    template: "%s · Soma",
  },
  applicationName: "Soma",
  description: "A personal atlas for sleep, recovery, movement, and training.",
  verification: {
    google: "vN4Hbw8JsncwAf_vQailk6Xw0Wrh7awEsPtmaVoJWL8",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "dark light",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#161913" },
    { media: "(prefers-color-scheme: light)", color: "#F2EFE6" },
  ],
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // A fresh request is required so Next.js can attach the per-request CSP nonce
  // generated by proxy.ts to framework and hydration scripts.
  await connection();
  const user = await getCurrentUser();
  const localPreview = isLocalPreviewMode();

  return (
    <html className={`${schibsted.variable} ${newsreader.variable} ${azeretMono.variable}`} lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body className={localPreview ? "local-preview" : undefined}>
        <ThemeInitializer />
        <SkipLink />
        {localPreview && <div className="preview-banner" role="status"><strong>LOCAL PREVIEW</strong><span>Demo Data · Nothing is sent or saved</span></div>}
        <AppShell user={user} localPreview={localPreview}>{children}</AppShell>
      </body>
    </html>
  );
}
