"use client";

import { Check, Database, Download, ExternalLink, LoaderCircle, LogOut, RefreshCw, Save, Shield, Trash2, Unplug } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

type Profile = { displayName: string; dateOfBirth: string; heightCm: number; weightKg: number; primaryGoal: string; baseSleepTargetMinutes: number; usualWakeTime: string; importRange: "90_days" | "all_history" };
const goals = { build_muscle: "Build muscle", improve_endurance: "Improve endurance", improve_cardio: "Improve cardio", general_fitness: "General fitness", maintain_health: "Maintain health", other: "Other" };

export function SettingsConsole({ demoMode }: { demoMode: boolean }) {
  const router = useRouter();
  const [tab, setTab] = useState<"profile" | "connections" | "privacy">("profile");
  const [profile, setProfile] = useState<Profile | null>(null);
  const [connection, setConnection] = useState<Record<string, unknown> | null>(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [deleteText, setDeleteText] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetch("/api/profile").then((response) => response.json()), fetch("/api/health/connection").then((response) => response.json())]).then(([profileData, connectionData]) => { setProfile(profileData); setConnection(connectionData.connection ?? null); }); }, []);
  function update<K extends keyof Profile>(key: K, value: Profile[K]) { setProfile((current) => current ? { ...current, [key]: value } : current); }
  async function save() { if (!profile) return; setSaving(true); const response = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); setSaving(false); setSaved(response.ok); setTimeout(() => setSaved(false), 1400); }
  async function sync() { setMessage("Sync started…"); const response = await fetch("/api/health/sync", { method: "POST" }); const result = await response.json(); setMessage(response.ok ? result.message ?? `Sync ${result.progress ?? 0}% complete.` : result.error); }
  async function disconnect() { if (!window.confirm("Disconnect Google Health? Imported Soma data will remain until you delete your account.")) return; const response = await fetch("/api/health/connection", { method: "DELETE" }); if (response.ok) { setConnection(null); setMessage("Google Health disconnected."); } }
  async function deleteAccount() { const response = await fetch("/api/account", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: deleteText }) }); const result = await response.json(); if (response.ok) { window.localStorage.clear(); setMessage(demoMode ? "Demo deletion completed locally." : "Your account and Soma data were deleted."); } else setMessage(result.error); }
  async function signOut() { await fetch("/api/auth/signout", { method: "POST" }); router.push("/login"); router.refresh(); }
  if (!profile) return <div className="workout-loading"><LoaderCircle className="spin" />Loading settings…</div>;
  return <div className="settings-page" id="main-page-content"><header><span className="eyebrow">Account and preferences</span><h1>Settings</h1><p>Manage the details, connections, and privacy choices that power your Soma experience.</p></header><div className="settings-layout"><nav aria-label="Settings sections"><button className={tab === "profile" ? "is-active" : ""} onClick={() => setTab("profile")} type="button">Profile & goals</button><button className={tab === "connections" ? "is-active" : ""} onClick={() => setTab("connections")} type="button">Connections</button><button className={tab === "privacy" ? "is-active" : ""} onClick={() => setTab("privacy")} type="button">Data & privacy</button></nav><section className="settings-content">{tab === "profile" && <section className="settings-card"><div><h2>Profile and targets</h2><p>These values support your personal estimates. They are not taken from Google automatically.</p></div><div className="settings-form"><label>Name<input value={profile.displayName} onChange={(event) => update("displayName", event.target.value)} /></label><label>Date of birth<input type="date" value={profile.dateOfBirth} onChange={(event) => update("dateOfBirth", event.target.value)} /></label><label>Height (cm)<input type="number" value={profile.heightCm} onChange={(event) => update("heightCm", Number(event.target.value))} /></label><label>Weight (kg)<input type="number" step="0.1" value={profile.weightKg} onChange={(event) => update("weightKg", Number(event.target.value))} /></label><label>Primary goal<select value={profile.primaryGoal} onChange={(event) => update("primaryGoal", event.target.value)}>{Object.entries(goals).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Base sleep target<select value={profile.baseSleepTargetMinutes} onChange={(event) => update("baseSleepTargetMinutes", Number(event.target.value))}><option value="420">7 hours</option><option value="450">7.5 hours</option><option value="480">8 hours</option><option value="510">8.5 hours</option><option value="540">9 hours</option></select></label><label>Usual wake time<input type="time" value={profile.usualWakeTime} onChange={(event) => update("usualWakeTime", event.target.value)} /></label><label>Initial import<select value={profile.importRange} onChange={(event) => update("importRange", event.target.value as Profile["importRange"])}><option value="90_days">Last 90 days</option><option value="all_history">All available history</option></select></label></div><button className="primary-button" onClick={() => void save()} disabled={saving} type="button">{saving ? <LoaderCircle className="spin" /> : saved ? <Check /> : <Save />} {saved ? "Saved" : "Save changes"}</button></section>}
  {tab === "connections" && <section className="settings-card"><div><h2>Health data connection</h2><p>Google sign-in and Google Health permission are separate. Soma requests read-only health scopes.</p></div><article className="connection-card"><span className="connection-logo">G</span><div><strong>Google Health</strong><p>{connection ? `Connected · Last sync ${connection.last_synced_at ? new Date(String(connection.last_synced_at)).toLocaleString("en-US") : "pending"}` : demoMode ? "Demo mode · no live account connected" : "Not connected"}</p></div>{connection ? <div className="connection-actions"><button onClick={() => void sync()} type="button"><RefreshCw />Sync now</button><button onClick={() => void disconnect()} type="button"><Unplug />Disconnect</button></div> : <a href="/api/health/google/connect">Connect <ExternalLink /></a>}</article><div className="scope-note"><Shield /><div><strong>Read-only by design</strong><p>Sleep, activity and fitness, and health metrics. OAuth tokens are encrypted and never sent to your browser.</p></div></div>{message && <p className="settings-message">{message}</p>}</section>}
  {tab === "privacy" && <section className="settings-card"><div><h2>Your Soma data</h2><p>Soma keeps your history until you export or delete it. Provider OAuth secrets are excluded from exports.</p></div><div className="privacy-actions"><article><Database /><div><strong>Export all data</strong><p>Download profile, normalized health records, scores, insights, conversations, and workouts as JSON.</p></div><a href="/api/account/export" download><Download />Export JSON</a></article><article><LogOut /><div><strong>Sign out</strong><p>End this browser session without deleting any data.</p></div><button onClick={() => void signOut()} type="button">Sign out</button></article><article className="danger-zone"><Trash2 /><div><strong>Delete account and all Soma data</strong><p>This permanently removes your Soma account. Enter DELETE MY SOMA DATA to confirm.</p><input value={deleteText} onChange={(event) => setDeleteText(event.target.value)} placeholder="DELETE MY SOMA DATA" /></div><button disabled={deleteText !== "DELETE MY SOMA DATA"} onClick={() => void deleteAccount()} type="button">Delete permanently</button></article></div>{message && <p className="settings-message">{message}</p>}</section>}</section></div></div>;
}
