"use client";

import { Check, ChevronLeft, ChevronRight, Dumbbell, LoaderCircle, Minus, Pause, Play, Plus, RotateCcw, Save, Timer, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Exercise = { id: string; name: string; muscle_groups: string[]; equipment: string[]; instructions: string[] };
type ProgramExercise = { exercise: Exercise; sets: number; repsMin: number; repsMax: number; restSeconds: number };
type Program = { id: string; name: string; description?: string; exercises: ProgramExercise[] };

function ExerciseFigure({ name }: { name: string }) {
  const mode = name.toLowerCase().includes("squat") ? "squat" : name.toLowerCase().includes("press") ? "press" : name.toLowerCase().includes("plank") ? "plank" : "hinge";
  return <div className={`exercise-figure exercise-figure--${mode}`} role="img" aria-label={`Original animated form guide for ${name}`}><svg viewBox="0 0 240 180" aria-hidden="true"><line className="floor" x1="30" y1="151" x2="210" y2="151" /><g className="figure-body"><circle cx="120" cy="35" r="14" /><line x1="120" y1="50" x2="120" y2="100" /><line x1="120" y1="62" x2="84" y2="83" /><line x1="120" y1="62" x2="156" y2="83" /><line x1="120" y1="100" x2="92" y2="145" /><line x1="120" y1="100" x2="148" y2="145" /><line className="weight" x1="63" y1="81" x2="177" y2="81" /></g></svg><span>Form guide · simplified illustration</span></div>;
}

function formatTimer(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`; }

export function WorkoutStudio() {
  const [exercises, setExercises] = useState<Exercise[]>([]);
  const [programs, setPrograms] = useState<Program[]>([]);
  const [selected, setSelected] = useState<ProgramExercise[]>([]);
  const [name, setName] = useState("Full Body A");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [builderOpen, setBuilderOpen] = useState(false);
  const [active, setActive] = useState<{ program: Program; sessionId: string; exerciseIndex: number; setIndex: number; elapsed: number; rest: number; paused: boolean } | null>(null);
  const activeSessionId = active?.sessionId;
  const activePaused = active?.paused;

  useEffect(() => { fetch("/api/workouts").then((response) => response.json()).then((data) => { setExercises(data.exercises ?? []); const local = window.localStorage.getItem("soma:workout-programs"); setPrograms(local ? JSON.parse(local) : data.programs ?? []); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!activeSessionId || activePaused) return; const timer = window.setInterval(() => setActive((current) => current ? { ...current, elapsed: current.elapsed + 1, rest: Math.max(0, current.rest - 1) } : null), 1000); return () => window.clearInterval(timer); }, [activePaused, activeSessionId]);

  function toggleExercise(exercise: Exercise) { setSelected((current) => current.some((item) => item.exercise.id === exercise.id) ? current.filter((item) => item.exercise.id !== exercise.id) : [...current, { exercise, sets: 3, repsMin: 8, repsMax: 12, restSeconds: 90 }]); }
  function updateExercise(id: string, key: keyof Omit<ProgramExercise, "exercise">, value: number) { setSelected((current) => current.map((item) => item.exercise.id === id ? { ...item, [key]: value } : item)); }
  async function saveProgram() { setSaving(true); const response = await fetch("/api/workouts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, exercises: selected.map((item) => ({ exerciseId: item.exercise.id, sets: item.sets, repsMin: item.repsMin, repsMax: item.repsMax, restSeconds: item.restSeconds })) }) }); const result = await response.json(); if (response.ok) { const program = { id: result.id, name, exercises: selected }; const next = [program, ...programs]; setPrograms(next); window.localStorage.setItem("soma:workout-programs", JSON.stringify(next)); setBuilderOpen(false); } setSaving(false); }
  async function start(program: Program) { const response = await fetch("/api/workouts/sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ programId: program.id, name: program.name }) }); const result = await response.json(); if (response.ok) setActive({ program, sessionId: result.id, exerciseIndex: 0, setIndex: 1, elapsed: 0, rest: 0, paused: false }); }
  const currentExercise = active?.program.exercises[active.exerciseIndex];
  async function completeSet() { if (!active || !currentExercise) return; await fetch(`/api/workouts/sessions/${active.sessionId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "complete_set", exercisePosition: active.exerciseIndex, setIndex: active.setIndex, completedReps: currentExercise.repsMin, weightKg: null }) }); const lastSet = active.setIndex >= currentExercise.sets; const lastExercise = active.exerciseIndex >= active.program.exercises.length - 1; if (lastSet && lastExercise) { await finish(); return; } setActive({ ...active, exerciseIndex: lastSet ? active.exerciseIndex + 1 : active.exerciseIndex, setIndex: lastSet ? 1 : active.setIndex + 1, rest: currentExercise.restSeconds }); }
  async function finish() { if (!active) return; await fetch(`/api/workouts/sessions/${active.sessionId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "complete", durationSeconds: active.elapsed }) }); setActive(null); }
  const totalSets = useMemo(() => programs.reduce((sum, program) => sum + program.exercises.reduce((inner, item) => inner + item.sets, 0), 0), [programs]);

  if (loading) return <div className="workout-loading"><LoaderCircle className="spin" /> Loading workout studio…</div>;
  return <div className="workout-page" id="main-page-content"><header className="workout-header"><div><span className="eyebrow">Training studio</span><h1>Workouts</h1><p>Build strength programs on desktop, then follow each set with mobile-friendly live controls.</p></div><button className="primary-button" type="button" onClick={() => setBuilderOpen(true)}><Plus size={17} />New program</button></header><section className="workout-summary"><article><span>Programs</span><strong>{programs.length}</strong></article><article><span>Planned sets</span><strong>{totalSets}</strong></article><article><span>Primary goal</span><strong>Build muscle</strong></article></section>{programs.length ? <section className="program-grid">{programs.map((program) => <article className="program-card" key={program.id}><div className="program-icon"><Dumbbell /></div><span>{program.exercises.length} exercises</span><h2>{program.name}</h2><ul>{program.exercises.slice(0, 4).map((item) => <li key={item.exercise.id}>{item.exercise.name}<span>{item.sets} × {item.repsMin}–{item.repsMax}</span></li>)}</ul><button type="button" onClick={() => void start(program)}><Play size={16} />Start workout</button></article>)}</section> : <section className="workout-empty"><Dumbbell size={28} /><h2>Create your first program</h2><p>Choose exercises, sets, repetitions, and rest. Soma will save the structure for repeat sessions.</p><button className="secondary-button" type="button" onClick={() => setBuilderOpen(true)}>Open builder</button></section>}
  {builderOpen && <div className="workout-modal" role="dialog" aria-modal="true" aria-labelledby="builder-title"><header><div><span className="eyebrow">Program builder</span><h2 id="builder-title">Design your session</h2></div><button className="icon-button" onClick={() => setBuilderOpen(false)} type="button" aria-label="Close builder"><X /></button></header><label className="builder-name">Program name<input value={name} onChange={(event) => setName(event.target.value)} /></label><div className="builder-layout"><section><h3>Exercise library</h3><div className="exercise-picker">{exercises.map((exercise) => <button className={selected.some((item) => item.exercise.id === exercise.id) ? "is-selected" : ""} key={exercise.id} onClick={() => toggleExercise(exercise)} type="button"><span>{exercise.name}<small>{exercise.muscle_groups.join(" · ")}</small></span>{selected.some((item) => item.exercise.id === exercise.id) ? <Check size={17} /> : <Plus size={17} />}</button>)}</div></section><section><h3>Program details</h3>{selected.length ? <div className="selected-exercises">{selected.map((item) => <article key={item.exercise.id}><strong>{item.exercise.name}</strong><div><label>Sets<input type="number" min="1" max="20" value={item.sets} onChange={(event) => updateExercise(item.exercise.id, "sets", Number(event.target.value))} /></label><label>Min reps<input type="number" min="1" value={item.repsMin} onChange={(event) => updateExercise(item.exercise.id, "repsMin", Number(event.target.value))} /></label><label>Max reps<input type="number" min="1" value={item.repsMax} onChange={(event) => updateExercise(item.exercise.id, "repsMax", Number(event.target.value))} /></label><label>Rest (sec)<input type="number" min="0" value={item.restSeconds} onChange={(event) => updateExercise(item.exercise.id, "restSeconds", Number(event.target.value))} /></label></div></article>)}</div> : <p className="empty-state">Select at least one exercise.</p>}</section></div><footer><button className="primary-button" disabled={!name.trim() || !selected.length || saving} onClick={() => void saveProgram()} type="button">{saving ? <LoaderCircle className="spin" /> : <Save size={17} />}Save program</button></footer></div>}
  {active && currentExercise && <div className="live-workout" role="dialog" aria-modal="true" aria-label="Live workout"><header><button type="button" onClick={() => setActive(null)} aria-label="Close workout"><X /></button><div><span>{active.program.name}</span><strong><Timer size={15} />{formatTimer(active.elapsed)}</strong></div><button type="button" onClick={() => setActive({ ...active, paused: !active.paused })} aria-label={active.paused ? "Resume workout timer" : "Pause workout timer"}>{active.paused ? <Play /> : <Pause />}</button></header><section className="live-workout-content"><div className="live-progress"><span>Exercise {active.exerciseIndex + 1} of {active.program.exercises.length}</span><span style={{ width: `${((active.exerciseIndex + active.setIndex / currentExercise.sets) / active.program.exercises.length) * 100}%` }} /></div><ExerciseFigure name={currentExercise.exercise.name} /><div className="live-title"><span>Set {active.setIndex} of {currentExercise.sets}</span><h1>{currentExercise.exercise.name}</h1><p>{currentExercise.repsMin}–{currentExercise.repsMax} reps · controlled form</p></div>{active.rest > 0 && <div className="rest-timer"><span>Rest</span><strong>{formatTimer(active.rest)}</strong><div><button type="button" onClick={() => setActive({ ...active, rest: Math.max(0, active.rest - 15) })}><Minus />15 sec</button><button type="button" onClick={() => setActive({ ...active, rest: active.rest + 15 })}><Plus />15 sec</button></div></div>}<button className="complete-set" type="button" onClick={() => void completeSet()}><Check />Complete set</button><div className="live-navigation"><button disabled={active.exerciseIndex === 0} type="button" onClick={() => setActive({ ...active, exerciseIndex: Math.max(0, active.exerciseIndex - 1), setIndex: 1 })}><ChevronLeft />Previous</button><button type="button" onClick={() => setActive({ ...active, rest: 0 })}><RotateCcw />Skip rest</button><button disabled={active.exerciseIndex === active.program.exercises.length - 1} type="button" onClick={() => setActive({ ...active, exerciseIndex: Math.min(active.program.exercises.length - 1, active.exerciseIndex + 1), setIndex: 1 })}>Next<ChevronRight /></button></div></section></div>}
  </div>;
}
