// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// @ts-expect-error The generated JavaScript module intentionally has no declaration file.
import openNextWorker from "../.open-next/worker.js";

type ScheduledControllerLike = { cron: string; scheduledTime: number };
type ExecutionContextLike = { waitUntil(promise: Promise<unknown>): void };
type WorkerEnv = {
  NEXT_PUBLIC_SITE_URL?: string;
  CRON_SECRET?: string;
  [key: string]: unknown;
};

const worker = {
  fetch: openNextWorker.fetch,

  async scheduled(_controller: ScheduledControllerLike, env: WorkerEnv, context: ExecutionContextLike) {
    if (!env.NEXT_PUBLIC_SITE_URL || !env.CRON_SECRET) {
      throw new Error("NEXT_PUBLIC_SITE_URL and CRON_SECRET are required for scheduled sync.");
    }
    const response = await openNextWorker.fetch(new Request(new URL("/api/cron/sync", env.NEXT_PUBLIC_SITE_URL), {
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    }), env, context);
    if (!response.ok) throw new Error(`Scheduled Soma sync failed with HTTP ${response.status}.`);
  },
};

export default worker;
