// Les identifiants anglais restent stables pour les imports et les données
// existantes ; ces libellés servent uniquement à l’affichage français.
const metricLabels: Record<string, string> = {
  sleep_minutes: "Sleep duration",
  sleep_need: "Estimated sleep need",
  sleep_efficiency: "Sleep efficiency",
  sleep_latency: "Sleep latency",
  sleep_awake: "Awake time",
  sleep_awake_percent: "Awake percentage",
  sleep_awakenings: "Awakenings",
  sleep_fragmentation: "Sleep fragmentation",
  deep_sleep: "Deep sleep",
  deep_sleep_percent: "Deep sleep percentage",
  rem_sleep: "REM sleep",
  rem_sleep_percent: "REM sleep percentage",
  light_sleep: "Light sleep",
  light_sleep_percent: "Light sleep percentage",
  hrv: "HRV",
  rhr: "Resting heart rate",
  respiratory: "Respiratory rate",
  spo2: "Oxygen saturation",
  spo2_low: "Low oxygen saturation",
  spo2_high: "High oxygen saturation",
  bedtime: "Bedtime",
  wake_time: "Wake time",
  sleep_regularity: "Sleep regularity",
  sleep_debt: "Sleep debt",
  daily_sleep_debt: "Daily sleep debt",
  steps: "Steps",
  zone_minutes: "Zone minutes",
  light_zone_minutes: "Light zone minutes",
  moderate_zone_minutes: "Moderate zone minutes",
  vigorous_zone_minutes: "Vigorous zone minutes",
  peak_zone_minutes: "Peak zone minutes",
  intense_minutes: "Intense zone minutes",
  active_minutes: "Active minutes",
  exercise_minutes: "Exercise minutes",
  skin_temperature: "Skin temperature deviation",
  night_temperature: "Night temperature",
  baseline_temperature: "Baseline temperature",
  active_energy: "Active energy",
  total_energy: "Total energy",
  sedentary_minutes: "Sedentary minutes",
  distance: "Distance",
  running_distance: "Running distance",
  running_pace: "Running pace",
  running_average_heart_rate: "Average running heart rate",
  floors: "Floors",
  weight: "Weight",
  body_fat: "Body fat",
  vo2_max: "VO₂ max",
  altitude_gain: "Elevation gain",
  height: "Height",
  core_temperature: "Core body temperature",
  blood_glucose: "Blood glucose",
  active_day: "Active day",
  run_day: "Running day",
  active_day_rate: "Active day rate",
  activity_consistency: "Activity consistency",
  weekly_load: "Weekly load",
  load_ratio: "Acute / chronic load ratio",
  recovery: "Recovery",
  effort: "Strain",
  meal_calories: "Meal calories",
  meal_protein: "Meal protein",
  meal_carbs: "Meal carbohydrates",
  meal_fat: "Meal fat",
  meal_fiber: "Meal fiber",
  meal_sugar: "Meal sugars",
  meal_added_sugar: "Meal added sugars",
  meal_count: "Logged meals",
  meal_coverage: "Meal coverage",
  meal_homemade_count: "Homemade meals",
  meal_prepared_count: "Prepared / bought meals",
  meal_mixed_count: "Mixed meals",
  meal_homemade_share: "Homemade meal share",
  meal_mouth_heat_average: "Mouth heat · average",
  meal_mouth_heat_maximum: "Mouth heat · maximum",
  meal_stomach_overfullness_average: "Meal fullness · average",
  meal_stomach_overfullness_maximum: "Meal fullness · maximum",
  meal_analysis_coverage: "Meal analysis coverage",
  meal_analysis_confidence: "Meal analysis confidence",
  meal_food_variety: "Distinct meal foods",
  meal_food_groups: "Meal food groups",
  vacation: "Vacation",
  illness: "Illness",
  breakfast: "Breakfast",
  "light breakfast": "Light breakfast",
  whm: "WHM",
  caffeine: "Caffeine",
  "added sugar": "Added sugar",
  masturbation: "Masturbation",
  running: "Running",
  alcohol: "Alcohol",
  "strength training": "Strength training",
  "dinner end time": "Dinner end time",
  magnesium: "Magnesium",
  "breathing exercise": "Breathing exercise",
  "reading for 20 minutes": "Reading for 20 minutes",
  "dark room": "Dark room",
  "late meal": "Late meal",
  nap: "Nap",
  meditation: "Meditation",
  travel: "Travel",
};

const metricUnits: Record<string, string> = {
  steps: "steps",
  floors: "floors",
  count: "occurrences",
  "yes/no": "yes/no",
  rounds: "rounds",
  drinks: "drinks",
};

const metricSentenceLabels: Record<string, string> = {
  wake_time: "Wake time",
  steps: "Steps",
  caffeine: "Caffeine",
  sleep_awake: "awake time",
  sleep_efficiency: "sleep efficiency",
  recovery: "recovery",
};

export function localizedMetricLabel(id: string, fallback: string) {
  return metricLabels[id.replace(/^journal:/, "").trim().toLocaleLowerCase("en")] ?? fallback;
}

export function localizedMetricSentenceLabel(id: string, fallback: string) {
  const key = id.replace(/^journal:/, "").trim().toLocaleLowerCase("en");
  return metricSentenceLabels[key] ?? localizedMetricLabel(id, fallback);
}

export function localizedMetricUnit(unit: string) {
  return metricUnits[unit.trim().toLocaleLowerCase("en")] ?? unit;
}
