// Les identifiants anglais restent stables pour les imports et les données
// existantes ; ces libellés servent uniquement à l’affichage français.
const metricLabels: Record<string, string> = {
  sleep_minutes: "Durée du sommeil",
  sleep_need: "Besoin de sommeil estimé",
  sleep_efficiency: "Efficacité du sommeil",
  sleep_latency: "Latence d’endormissement",
  sleep_awake: "Temps éveillé",
  sleep_awake_percent: "Part éveillée",
  sleep_awakenings: "Réveils",
  sleep_fragmentation: "Fragmentation du sommeil",
  deep_sleep: "Sommeil profond",
  deep_sleep_percent: "Part de sommeil profond",
  rem_sleep: "Sommeil paradoxal",
  rem_sleep_percent: "Part de sommeil paradoxal",
  light_sleep: "Sommeil léger",
  light_sleep_percent: "Part de sommeil léger",
  hrv: "VFC",
  rhr: "Fréquence cardiaque au repos",
  respiratory: "Fréquence respiratoire",
  spo2: "Saturation en oxygène",
  spo2_low: "Saturation en oxygène basse",
  spo2_high: "Saturation en oxygène haute",
  bedtime: "Heure du coucher",
  wake_time: "Heure du réveil",
  sleep_regularity: "Régularité du sommeil",
  sleep_debt: "Dette de sommeil",
  daily_sleep_debt: "Écart de sommeil quotidien",
  steps: "Pas",
  zone_minutes: "Minutes en zone",
  light_zone_minutes: "Minutes en zone légère",
  moderate_zone_minutes: "Minutes en zone modérée",
  vigorous_zone_minutes: "Minutes en zone vigoureuse",
  peak_zone_minutes: "Minutes en zone maximale",
  intense_minutes: "Minutes en zones intenses",
  active_minutes: "Minutes actives",
  exercise_minutes: "Minutes d’exercice",
  skin_temperature: "Écart de température cutanée",
  night_temperature: "Température nocturne",
  baseline_temperature: "Température de référence",
  active_energy: "Énergie active",
  total_energy: "Énergie totale",
  sedentary_minutes: "Minutes sédentaires",
  distance: "Distance",
  running_distance: "Distance de course",
  running_pace: "Allure de course",
  running_average_heart_rate: "Fréquence cardiaque moyenne en course",
  floors: "Étages",
  weight: "Poids",
  body_fat: "Masse grasse",
  vo2_max: "VO₂ max",
  altitude_gain: "Dénivelé positif",
  height: "Taille",
  core_temperature: "Température corporelle centrale",
  blood_glucose: "Glycémie",
  active_day: "Journée active",
  run_day: "Journée de course",
  active_day_rate: "Taux de journées actives",
  activity_consistency: "Régularité de l’activité",
  weekly_load: "Charge hebdomadaire",
  load_ratio: "Charge aiguë / chronique",
  recovery: "Récupération",
  effort: "Effort",
  meal_calories: "Calories des repas",
  meal_protein: "Protéines des repas",
  meal_carbs: "Glucides des repas",
  meal_fat: "Lipides des repas",
  meal_fiber: "Fibres des repas",
  meal_sugar: "Sucres des repas",
  meal_added_sugar: "Sucres ajoutés des repas",
  meal_count: "Repas enregistrés",
  meal_coverage: "Couverture des repas",
  meal_homemade_count: "Repas faits maison",
  meal_prepared_count: "Repas préparés / achetés",
  meal_mixed_count: "Repas mixtes",
  meal_homemade_share: "Part de repas faits maison",
  meal_mouth_heat_average: "Chaleur en bouche · moyenne",
  meal_mouth_heat_maximum: "Chaleur en bouche · maximum",
  meal_stomach_overfullness_average: "Surcharge du repas · moyenne",
  meal_stomach_overfullness_maximum: "Surcharge du repas · maximum",
  meal_analysis_coverage: "Couverture de l’analyse des repas",
  meal_analysis_confidence: "Confiance de l’analyse des repas",
  meal_food_variety: "Aliments distincts des repas",
  meal_food_groups: "Groupes alimentaires des repas",
  vacation: "Vacances",
  illness: "Maladie",
  breakfast: "Petit déjeuner",
  "light breakfast": "Petit-déjeuner léger",
  whm: "WHM",
  caffeine: "Caféine",
  "added sugar": "Sucres ajoutés",
  masturbation: "Masturbation",
  running: "Running détecté",
  alcohol: "Alcool",
  "strength training": "Musculation",
  "dinner end time": "Heure de fin du dîner",
  magnesium: "Magnésium",
  "breathing exercise": "Exercice de respiration",
  "reading for 20 minutes": "Lecture 20 minutes",
  "dark room": "Chambre sombre",
  "late meal": "Repas tardif",
  nap: "Sieste",
  meditation: "Méditation",
  travel: "Voyage",
};

const metricUnits: Record<string, string> = {
  steps: "pas",
  floors: "étages",
  count: "occurrences",
  "yes/no": "oui/non",
  rounds: "cycles",
  drinks: "verres",
};

const metricSentenceLabels: Record<string, string> = {
  wake_time: "L’heure de réveil",
  steps: "Les pas",
  caffeine: "La caféine",
  sleep_awake: "le temps éveillé",
  sleep_efficiency: "l’efficacité du sommeil",
  recovery: "la récupération",
};

export function localizedMetricLabel(id: string, fallback: string) {
  return metricLabels[id.replace(/^journal:/, "").trim().toLocaleLowerCase("en")] ?? fallback;
}

export function localizedMetricSentenceLabel(id: string, fallback: string) {
  const key = id.replace(/^journal:/, "").trim().toLocaleLowerCase("en");
  return metricSentenceLabels[key] ?? localizedMetricLabel(id, fallback);
}

export function localizedMetricUnit(unit: string) {
  return metricUnits[unit.trim().toLocaleLowerCase("en")] ?? unit;
}
